'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PORevisionExportMonthly

    '''<summary>
    '''ASPxLabel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel3 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''dtPeriodFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtPeriodFrom As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''ASPxLabel7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel7 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''rblCommercial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblCommercial As Global.DevExpress.Web.ASPxEditors.ASPxRadioButtonList

    '''<summary>
    '''ASPxLabel28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel28 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cboDeliveryLoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDeliveryLoc As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''txtDeliveryLoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDeliveryLoc As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''ASPxLabel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel2 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtPOEmergency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPOEmergency As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''ASPxLabel27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel27 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtShipBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShipBy As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''ASPxLabel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel1 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cboAffiliateCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboAffiliateCode As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''txtAffiliateName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAffiliateName As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''ASPxLabel26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel26 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cboSupplierCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboSupplierCode As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''txtSupplierName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSupplierName As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''btnRefresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRefresh As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btnClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClear As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''ASPxLabel6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel6 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtRevisionNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRevisionNo As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfo As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lSuuplier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lSuuplier As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ASPxLabel21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel21 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lSuuplier0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lSuuplier0 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ASPxLabel24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel24 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''ASPxLabel25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel25 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''ASPxTextBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBox1 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''ASPxTextBox2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBox2 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''ASPxTextBox3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBox3 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''ASPxTextBox4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBox4 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''ASPxTextBox5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBox5 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''txtOrderNoWeek1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOrderNoWeek1 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''txtOrderNoWeek2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOrderNoWeek2 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''txtOrderNoWeek3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOrderNoWeek3 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''txtOrderNoWeek4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOrderNoWeek4 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''txtOrderNoWeek5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOrderNoWeek5 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''ASPxTextBox6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBox6 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''dtWeekETDVendorOld1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtWeekETDVendorOld1 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''dtWeekETDVendorOld2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtWeekETDVendorOld2 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''dtWeekETDVendorOld3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtWeekETDVendorOld3 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''dtWeekETDVendorOld4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtWeekETDVendorOld4 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''dtWeekETDVendorOld5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtWeekETDVendorOld5 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''ASPxTextBox10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBox10 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''dtWeekETDVendor1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtWeekETDVendor1 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''dtWeekETDVendor2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtWeekETDVendor2 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''dtWeekETDVendor3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtWeekETDVendor3 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''dtWeekETDVendor4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtWeekETDVendor4 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''dtWeekETDVendor5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtWeekETDVendor5 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''ASPxTextBox7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBox7 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''dtWeekETDPortOld1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtWeekETDPortOld1 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''dtWeekETDPortOld2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtWeekETDPortOld2 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''dtWeekETDPortOld3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtWeekETDPortOld3 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''dtWeekETDPortOld4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtWeekETDPortOld4 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''dtWeekETDPortOld5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtWeekETDPortOld5 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''ASPxTextBox11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBox11 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''dtWeekETDPort1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtWeekETDPort1 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''dtWeekETDPort2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtWeekETDPort2 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''dtWeekETDPort3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtWeekETDPort3 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''dtWeekETDPort4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtWeekETDPort4 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''dtWeekETDPort5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtWeekETDPort5 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''ASPxTextBox8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBox8 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''dtWeekETAPortOld1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtWeekETAPortOld1 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''dtWeekETAPortOld2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtWeekETAPortOld2 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''dtWeekETAPortOld3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtWeekETAPortOld3 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''dtWeekETAPortOld4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtWeekETAPortOld4 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''dtWeekETAPortOld5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtWeekETAPortOld5 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''ASPxTextBox12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBox12 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''dtWeekETAPort1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtWeekETAPort1 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''dtWeekETAPort2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtWeekETAPort2 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''dtWeekETAPort3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtWeekETAPort3 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''dtWeekETAPort4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtWeekETAPort4 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''dtWeekETAPort5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtWeekETAPort5 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''ASPxTextBox9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBox9 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''dtETAFactWeekOld1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtETAFactWeekOld1 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''dtETAFactWeekOld2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtETAFactWeekOld2 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''dtETAFactWeekOld3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtETAFactWeekOld3 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''dtETAFactWeekOld4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtETAFactWeekOld4 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''dtETAFactWeekOld5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtETAFactWeekOld5 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''ASPxTextBox13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBox13 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''dtETAFactWeek1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtETAFactWeek1 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''dtETAFactWeek2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtETAFactWeek2 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''dtETAFactWeek3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtETAFactWeek3 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''dtETAFactWeek4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtETAFactWeek4 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''dtETAFactWeek5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtETAFactWeek5 As Global.DevExpress.Web.ASPxEditors.ASPxTimeEdit

    '''<summary>
    '''grid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grid As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''btnSubMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubMenu As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btnSendSupplier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSendSupplier As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmit As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''ge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ge As Global.DevExpress.Web.ASPxGlobalEvents.ASPxGlobalEvents

    '''<summary>
    '''ButtonApprove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonApprove As Global.DevExpress.Web.ASPxCallback.ASPxCallback

    '''<summary>
    '''cbSupplier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbSupplier As Global.DevExpress.Web.ASPxCallback.ASPxCallback

    '''<summary>
    '''ButtonPartNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonPartNo As Global.DevExpress.Web.ASPxCallback.ASPxCallback
End Class
