Public Class clsForecast
    Public Property D_Period As Date
    Public Property D_AffiliateID As String
    Public Property D_Rev As Integer
    Public Property D_PartNo As String
    Public Property D_ForecastQty1 As Double
    Public Property D_ForecastQty2 As Double
    Public Property D_ForecastQty3 As Double
    Public Property D_ForecastQty4 As Double
    Public Property D_F1 As Double
    Public Property D_F2 As Double
    Public Property D_F3 As Double
    Public Property D_F4 As Double
    Public Property D_F5 As Double
    Public Property D_F6 As Double
    Public Property D_F7 As Double
    Public Property D_F8 As Double
    Public Property D_F9 As Double
    Public Property D_F10 As Double
    Public Property D_F11 As Double
    Public Property D_F12 As Double
    Public Property D_F13 As Double
    Public Property D_F14 As Double
    Public Property D_F15 As Double
    Public Property D_F16 As Double
    Public Property D_F17 As Double
    Public Property D_F18 As Double
    Public Property D_F19 As Double
    Public Property D_F20 As Double
    Public Property D_F21 As Double
    Public Property D_F22 As Double
    Public Property D_F23 As Double
    Public Property D_F24 As Double
    Public Property D_F25 As Double
    Public Property D_F26 As Double
    Public Property D_F27 As Double
    Public Property D_F28 As Double
    Public Property D_F29 As Double
    Public Property D_F30 As Double
    Public Property D_F31 As Double
End Class
